# THE COMPILER BUILDS ITSELF. `build/avra` is the working binary and
# `make avra` rebuilds it with the binary already there; a cold tree
# bootstraps from the seed (`make bootstrap`, or `./avra` on its own).
# What links what:
#   build/llvm_wrapper.o  OURS — backend/llvm_wrapper.c, the
#                         compiler's LLVM binding; new builders are
#                         added there, never hunted for upstream.
#   build/avra_runtime.o  OURS — runtime/avra_runtime.c, the native
#                         half of the LANGUAGE's semantics; the only
#                         runtime avra-built programs link.

LLVM_PREFIX ?= /opt/homebrew/opt/llvm
# a manifest's link flags name it as ${LLVM_PREFIX}
export LLVM_PREFIX

RUNTIME_OBJS := build/llvm_wrapper.o build/avra_runtime.o

# Every package that carries spec cases, in dependency order.
SUITES := packages/std-errors packages/std-testing packages/std-text packages/std-path packages/std-time packages/std-io packages/std-toml packages/std-process packages/std-cli packages/std-json packages/std-avrac packages/cli packages/std-sqlite

.PHONY: census traps test tested clean gate externs idioms idioms-accept bench fuzz scaffold-check vocab sweep seed bootstrap \
        check run ir emit build-native native-check avra

# THE COMPILER, BUILT BY ITSELF: the binary in build/ compiles the
# tree into the next one. `./avra` prefers it and bootstraps a cold
# tree only.
# THE SEED: the compiler, emitted, so the chain cannot be lost.
# `make bootstrap` builds a compiler from it and then rebuilds from
# source; `make seed` refreshes it. bootstrap/README.md holds the rule.
#
# THE DEFAULT GOAL IS NAMED, because make's own default is the FIRST
# TARGET and that is `seed` — so a bare `make`, or `make -p` to read a
# variable, silently rewrote the committed 9.5 MB bootstrap with
# whatever the standing binary emitted. A seed regenerated by accident
# is a seed nobody chose, and it is large enough to ride into a commit
# unread.
.DEFAULT_GOAL := avra

seed: $(RUNTIME_OBJS)
	@./avra emit packages/cli > bootstrap/seed.ll
	@echo "seed: bootstrap/seed.ll ($$(wc -l < bootstrap/seed.ll | tr -d ' ') lines)"

# THE ONLY RULE THAT LINKS BY HAND, and the one a cold tree and every
# recovery must take — `seed` and `avra` link through the compiler.
# So the object list is named ONCE: a prerequisite and a link line
# spelling it twice were two definitions nothing kept in step, and the
# gap opens silently the instant the variable grows.
bootstrap: $(RUNTIME_OBJS)
	@mkdir -p build
	@clang -w -O1 bootstrap/seed.ll $(RUNTIME_OBJS) \
	    -L$(LLVM_PREFIX)/lib -lLLVM -o build/avra
	@codesign -f -s - build/avra 2>/dev/null || true
	@echo "bootstrap: build/avra from the seed — rebuilding from source"
	@$(MAKE) -s avra

# A REFUSAL MUST SPEAK: the build's own words went to /dev/null, so a compiler
# that refused its own source reported only "make: *** Error 2" and the next
# reader ran `./avra build packages/cli` by hand to find out why.
avra: $(RUNTIME_OBJS)
	@mkdir -p build
	@: > build/avra-build.out
	@./avra build packages/cli >> build/avra-build.out 2>&1 || { tail -c 200000 build/avra-build.out; exit 1; }
	@mkdir -p build
	@cp packages/cli/src/main build/avra
	@codesign -f -s - build/avra 2>/dev/null || true
	@rm -f packages/cli/src/main packages/cli/src/main.av.ll
	@echo "avra: build/avra"

# Scratch a run leaves behind: the test binaries each package's
# cases were linked into.
sweep:
	@find packages -type d -name build -prune -exec rm -rf {} +
	@rm -rf build/test_shards

test: $(RUNTIME_OBJS) build/sqlite3.o build/sqlite_sentinel.o
	@for p in $(SUITES); do \
	  ./avra test $$p || exit 1; \
	done

# THE OBJECT FOLLOWS THE SOURCE'S CONTENT, NOT ITS TIMESTAMP. make
# compares mtimes at ONE-SECOND granularity, so a stash-and-rebuild
# cycle that lands inside one second leaves the object looking current
# while the source has changed under it — and `make gate` then reports
# the PARENT's behaviour over a tree that carries the change. That
# happened landing f57372a: 39/46 in std-text with the fix on disk,
# and it read as "my change is broken" rather than "the object is
# stale". Reproduced deterministically with `touch -r`.
# THE GATE IS THE RECEIPT, and a receipt for a tree nobody has is
# worse than no receipt. The stamp is rewritten only when the hash
# CHANGES, so its mtime moves on content and nothing else, and a
# repeated build recompiles nothing. One cost, stated: the stamp
# depends on FORCE, so `make -q` always reports work pending for these
# objects even when none is — nothing here reads `make -q`, and the
# alternative is to trust the timestamps again.
.PHONY: FORCE
FORCE:

build/%.sha: FORCE
	@mkdir -p build
	@shasum -a 256 $(SHA_SRC) | cut -d' ' -f1 > $@.tmp
	@cmp -s $@.tmp $@ 2>/dev/null || mv $@.tmp $@
	@rm -f $@.tmp

build/runtime.sha: SHA_SRC := runtime/avra_runtime.c
build/llvm_wrapper.sha: SHA_SRC := backend/llvm_wrapper.c

build/avra_runtime.o: runtime/avra_runtime.c build/runtime.sha
	@mkdir -p build
	cc -O2 -Wall -Werror -c runtime/avra_runtime.c -o build/avra_runtime.o

# The runtime's trap contract: the words and the verdict (exit 2).
# No program test can hold it — a suite runs every program in
# one process, and a trap ends it. AFTER `tested`, because a row may
# depend on a package: a broken package should fail its OWN suite
# first, not this keeper, which would name the harness for someone
# else's defect.
traps: $(RUNTIME_OBJS)
	@sh tools/traps.sh

# Exact refcount and list-write counts; the shipping runtime is put
# back on every exit.   make census CMD="check packages/std-avrac"
census:
	@sh tools/census.sh $(CMD)

build/llvm_wrapper.o: backend/llvm_wrapper.c build/llvm_wrapper.sha
	@mkdir -p build
	cc -c -O2 -I$(LLVM_PREFIX)/include -o build/llvm_wrapper.o backend/llvm_wrapper.c

clean:
	rm -rf build scratch packages/cli/src/main_stamped.av
	find packages -name "*.av.ll" -delete
	find packages -type d -name build -prune -exec rm -rf {} +

check: $(RUNTIME_OBJS)
	@./avra check $(FILE)

run: $(RUNTIME_OBJS)
	@./avra run $(FILE)

ir: $(RUNTIME_OBJS)
	@./avra ir $(FILE)

emit: $(RUNTIME_OBJS)
	@./avra emit $(FILE)

build-native: $(RUNTIME_OBJS)
	@./avra build $(FILE)

# The idiom bar: the baseline LISTS sites and only ever shrinks —
# `idioms-accept` prunes what is fixed and can never add. A new
# violation is written idiomatically or licensed AT the site.
idioms:
	@sh tools/idioms.sh

idioms-accept:
	@sh tools/idioms.sh --accept

# The IR vocabulary's guarantee: every Ins consumer stays exhaustive,
# so a new instruction cannot ship half-implemented.
vocab:
	@sh tools/vocab.sh

# A fingerprint tag NAMES a node kind: inside one fold space no two
# kinds may wear one number, or they fingerprint alike by construction.
fingerprints:
	@python3 tools/fingerprints.py

# THE EXTERN WALL'S WIDTH: Avra's `int` is 64 bits and C's is 32, so a
# C body answering a narrow type writes only the low half and a
# negative value reads as a large positive one. Both engines agree on
# that wrong answer, so a program test cannot catch it.
externs:
	@python3 tools/externs.py

# THE WIDTH WITNESS. C bodies that answer NARROWER than 64 bits, read
# twice from ONE object — by Avra through the extern seam, and by a C
# main. Identical output means the seam honours every declared width;
# a difference names the BOUNDARY rather than the object, which a
# single reader cannot do. It lives outside runtime/ because `make
# externs` refuses a narrow body WE own, and rightly: the defect under
# test is C someone else compiled. When a package can build its own
# native sources (ROADMAP: B7) this rule dies and the manifest's
# `sources` does the work.
# THE VENDORED SQLITE, one translation unit. `@std/sqlite`'s manifest
# names this object in its `[link]`, so the package cannot be checked,
# tested or linked without it — and it had no rule at all: the recipe
# lived in `vendor/FLAGS.md` as prose, main carried no object, and the
# package's whole suite sat outside `make gate` because nothing could
# build what it links.
#
# THE FLAG SET LIVES HERE, and the suite is what keeps it honest:
# `sqlite_test.av`'s `promised()` asks the LIBRARY for every flag below
# through `sqlite3_compileoption_used`, so the document, this rule and
# the object cannot drift without a red test. `vendor/FLAGS.md` carries
# the REASON for each; this carries the flag.
SQLITE_FLAGS := \
  -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_PREUPDATE_HOOK=1 \
  -DSQLITE_ENABLE_SESSION=1 -DSQLITE_ENABLE_SNAPSHOT=1 \
  -DSQLITE_ENABLE_NORMALIZE=1 -DSQLITE_ENABLE_STMT_SCANSTATUS=1 \
  -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_ENABLE_FTS5=1 \
  -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_GEOPOLY=1 \
  -DSQLITE_ENABLE_MATH_FUNCTIONS=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 \
  -DSQLITE_ENABLE_DBPAGE_VTAB=1 -DSQLITE_ENABLE_BYTECODE_VTAB=1 \
  -DSQLITE_ENABLE_STAT4=1 -DSQLITE_ENABLE_EXPLAIN_COMMENTS=1 \
  -DSQLITE_ENABLE_OFFSET_SQL_FUNC=1 -DSQLITE_DQS=0 \
  -DSQLITE_ENABLE_API_ARMOR=1 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS=1 \
  -DSQLITE_STRICT_SUBTYPE=1 -DSQLITE_DEFAULT_FOREIGN_KEYS=1 \
  -DSQLITE_THREADSAFE=1 -DSQLITE_MAX_EXPR_DEPTH=1000 \
  -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 \
  -DSQLITE_DEFAULT_MMAP_SIZE=268435456 -DSQLITE_MAX_MMAP_SIZE=1099511627776 \
  -DSQLITE_DEFAULT_CACHE_SIZE=-8000 -DSQLITE_DEFAULT_WORKER_THREADS=0 \
  -DNDEBUG=1

build/sqlite3.o: packages/std-sqlite/vendor/sqlite3.c
	@mkdir -p build
	cc -c -O2 $(SQLITE_FLAGS) -o $@ $<

# The driver's own C: the destructor sentinel as a named door, so no
# Avra program needs a way to build a pointer from an integer.
# THE STEM IS THE C FILE'S STEM, so the package-C standard's generic
# rule can replace this hand rule by deleting it.
build/sqlite_sentinel.o: packages/std-sqlite/src/c/sqlite_sentinel.c
	@mkdir -p build
	cc -c -O2 -Ipackages/std-sqlite/vendor -o $@ $<

build/width_witness.o: packages/width-witness/src/witness.c
	@mkdir -p build
	cc -c -O2 -o build/width_witness.o packages/width-witness/src/witness.c

# EVERY WORKING FILE LIVES IN `build/`, WHICH IS PER-WORKTREE. A
# shared `/tmp` path is written by one lane and read by another: the
# `.out` files here are DIFFED, and every worktree runs the same
# witness, so a clobber between two lanes comparing the same program
# is a false PASS rather than a noisy failure. `build/witness-c` was
# the sharpest — a BINARY one lane compiled and another could run,
# under a rule whose whole claim is "Avra == C on the SAME object".
# The build LOCK stays in /tmp by design: it is machine-wide.
witness: $(RUNTIME_OBJS) build/width_witness.o
	@./avra build packages/width-witness > build/witness.path 2>&1 \
	  || { echo "witness: build FAILED"; cat build/witness.path; exit 1; }
	@$$(tail -1 build/witness.path) > build/witness-avra.out
	@cc -O2 -o build/witness-c packages/width-witness/src/reader.c build/width_witness.o
	@build/witness-c > build/witness-c.out
	@diff build/witness-c.out build/witness-avra.out \
	  || { echo "witness: Avra and C disagree on the same object — the extern seam lost a width"; exit 1; }
	@echo "witness: Avra == C on the same object — $$(cat build/witness-avra.out)"

# The whole gate: the vocabulary's guarantee, idioms, then every
# proof a package carries — its spec cases and its program tests,
# both inside its own suite.
# THE GATE: the suites run with the scaffolder's template in place —
# scaffolded into std-avrac before, removed after, however the suites
# end — so the templates' own test is one case of that suite, not a
# second compile of the whole compiler for one case.
gate: vocab fingerprints externs idioms tested traps witness

tested: $(RUNTIME_OBJS)
	@rm -rf packages/std-avrac/src/features/zz_probe
	@./avra new feature zz_probe > build/scaffold-new.out 2>&1 || { cat build/scaffold-new.out; exit 1; }
	@trap 'rm -rf packages/std-avrac/src/features/zz_probe' EXIT INT TERM; $(MAKE) -s test

# The differential gate: the compiled binary must say exactly what
# the evaluator says.
native-check: $(RUNTIME_OBJS)
	@./avra run $(FILE) > build/native-check-eval.out
	@./avra build $(FILE) > build/native-check-bin.path 2> build/native-check-bin.err
	@"$$(cat build/native-check-bin.path)" > build/native-check-native.out
	@diff build/native-check-eval.out build/native-check-native.out && echo "native == eval"

# The measured curve: the suites' wall time.
bench: $(RUNTIME_OBJS)
	@sh tools/bench.sh

# Mutated program tests through `avra check`: diagnose, never crash.
fuzz: $(RUNTIME_OBJS)
	@sh tools/fuzz.sh

# The scaffolder's templates must stay compilable: scaffold a
# throwaway feature, run the suite with it in the tree, remove it.
scaffold-check: $(RUNTIME_OBJS)
	@rm -rf packages/std-avrac/src/features/zz_probe
	@./avra new feature zz_probe > build/scaffold-new.out 2>&1 || { cat build/scaffold-new.out; exit 1; }
	@./avra test packages/std-avrac/src/features/zz_probe/tests/zz_probe_test.av > build/scaffold.out 2>&1; s=$$?; \
	  rm -rf packages/std-avrac/src/features/zz_probe; \
	  if [ $$s -ne 0 ]; then echo "scaffold-check FAILED"; tail -20 build/scaffold.out; exit 1; fi; \
	  echo "scaffold-check: the templates compile and their test passes"
