#!/usr/bin/env python3
"""Write the routes benchmark's source.

A slope reasoned past its last measured point is a claim, not a
measurement, so the sweep measures 3, 30 and 300 routes rather than
extrapolating from 8. Three hundred grammar declarations are not
worth hand-writing and are worth re-running, so they are generated
here and the generator lives beside the bench.

    python3 tools/bench/routes/generate.py > tools/bench/routes/src/main.av
"""
import sys

N = 300
SIZES = [3, 30, 300]
WORDS = ["alpha", "bravo", "charlie", "delta", "echo", "foxtrot", "golf", "hotel",
         "india", "juliet", "kilo", "lima", "mike", "november", "oscar", "papa"]


def name(i):
    """A route's own word — distinct, and a legal Avra name."""
    return "%s%d" % (WORDS[i % len(WORDS)], i // len(WORDS))


out = []
w = out.append

w('//! WHAT A LINEAR ROUTE SCAN COSTS as the table grows — the number a')
w('//! trie has to beat before it earns its keep. Every measurement hits')
w("//! the LAST route in the table, which is the scan's worst case and")
w("//! the trie's best argument.")
w('//!')
w('//! GENERATED by `generate.py` beside this file. Three hundred routes')
w('//! are not worth hand-writing and the sweep is worth re-running, so')
w('//! the generator is the source and this file is its output.')
w('use @std.http.frame.{framed, limits, Method, Head}')
w('use @std.http.http.{Request, Response, text}')
w('use @std.http.route.{Route, routed, dispatch}')
w('use @std.time.{now_ns}')
w('')
for i in range(N):
    w('grammar G%d = "/%s/{x}"' % (i, name(i)))
w('')
for i in range(N):
    w('fn h%d(q: Request, r: G%d) -> Response { text(200, r.x) }' % (i, i))
w('')
w('/// Every route, the one the target names LAST — so a scan of n pays')
w('/// n parses and a trie would pay one lookup.')
w('fn all() -> List<Route> {')
w('    [' + ',\n     '.join(
    'routed<G%d>(Method.Get, "/%s/{x}", (t: Bytes) -> G%d.parse(t), h%d)' % (i, name(i), i, i)
    for i in range(N)) + ']')
w('}')
w('')
w('fn asked(line: string) -> Request {')
w('    let raw = (line + "\\r\\nHost: h\\r\\n\\r\\n").bytes()')
w('    match framed(raw, 0, 0, limits()) {')
w('        .Complete(head) -> Request { raw: raw, head: head, body: "".bytes(), peer: "b" },')
w('        .Partial -> asked(line),')
w('        .Refused(_) -> asked(line),')
w('    }')
w('}')
w('')
w('fn scanned(rows: List<Route>, q: Request, runs: int) -> int {')
w('    mut ok = 0')
w('    // LICENSED I3: a timed loop counts, it does not build a list')
w('    for i in 0..runs {')
w('        if dispatch(rows, q).status == 200 { ok = ok + 1 }')
w('    }')
w('    ok')
w('}')
w('')
w('/// Nanoseconds per dispatch, or -1 when a run did not answer 200 —')
w('/// so a table that never matched cannot read as a fast one.')
w('fn cost(rows: List<Route>, line: string, runs: int) -> int {')
w('    let q = asked(line)')
w('    let start = now_ns()')
w('    let ok = scanned(rows, q, runs)')
w('    let spent = now_ns() - start')
w('    if ok != runs { return 0 - 1 }')
w('    spent / runs')
w('}')
w('')
w('let runs = 50000')
w('let every = all()')
w('let target = "GET /%s/7 HTTP/1.1"' % name(N - 1))
for n in SIZES:
    w('let at%d = cost(every.slice(%d, %d), target, runs)' % (n, N - n, N))
w('"runs ${runs}, hitting the LAST route | ' +
  ' | '.join('%d routes ${at%d} ns' % (n, n) for n in SIZES) + '"')

sys.stdout.write("\n".join(out) + "\n")
