#!/usr/bin/env python3
"""Write the routes benchmark's source.

Two questions, one program so the two answers share a machine and a
minute: what a LINEAR SCAN costs as the table grows, and what the
COMPILED TABLE costs on the same routes.

A slope reasoned past its last measured point is a claim, so the
sweep measures 3, 30 and 300 rather than extrapolating from 8. And a
measurement generalised past what it measured is a claim too, so the
table is measured on THREE SHAPES, not only the one that flatters it:

    flat   /alpha0/{x}            distinct first segments — one step decides
    deep   /api/v1/alpha0/{x}     a shared prefix — the step that decides is the third
    wild   /{tenant}/alpha0/{x}   a HOLE first — every route stays live past step one

Three hundred grammar declarations per shape are not worth
hand-writing and the sweep is worth re-running, so the generator is
the source and the .av file is its output, written canonical: the
generator lays the program out and `avra fmt` prints it.

    python3 tools/bench/routes/generate.py
"""
import os
import subprocess

N = 300
SIZES = [3, 30, 300]
WORDS = ["alpha", "bravo", "charlie", "delta", "echo", "foxtrot", "golf", "hotel",
         "india", "juliet", "kilo", "lima", "mike", "november", "oscar", "papa"]

SHAPES = [
    ("flat", "/%s/{x}",              "/%s/7"),
    ("deep", "/api/v1/%s/{x}",       "/api/v1/%s/7"),
    ("wild", "/{tenant}/%s/{x}",     "/acme/%s/7"),
]


def name(i):
    """A route's own word — distinct, and a legal Avra name."""
    return "%s%d" % (WORDS[i % len(WORDS)], i // len(WORDS))


out = []
w = out.append

w('//! WHAT A LINEAR ROUTE SCAN COSTS as the table grows, and what the')
w('//! COMPILED TABLE costs on the same routes — measured in one program')
w('//! so the two answers share a machine and a minute. Every')
w('//! measurement hits the LAST route in the table, which is the')
w("//! scan's worst case and the table's best argument.")
w('//!')
w('//! THREE SHAPES, because a table of distinct first segments is the')
w('//! one case a one-level index would already win: `deep` shares a')
w('//! prefix so the deciding step is the third, and `wild` opens with a')
w('//! HOLE so every route stays live past step one.')
w('//!')
w('//! GENERATED by `generate.py` beside this file.')
w('use @std.http.frame.{framed, limits, Method, Head}')
w('use @std.http.http.{Request, Unrouted, Response, text, status}')
w('use @std.http.body.{Body}')
w('use @std.http.route.{Route, Table, routed, compiled, dispatch, segments}')
w('use @std.time.{now_ns}')
w('')
for tag, pat, _ in SHAPES:
    for i in range(N):
        w('grammar %s%d = "%s"' % (tag.upper(), i, pat % name(i)))
    w('')
for tag, _, _ in SHAPES:
    for i in range(N):
        w('fn h_%s%d(q: Request<%s%d>) -> Response { text(200, q.params.x) }' % (tag, i, tag.upper(), i))
    w('')
for tag, pat, _ in SHAPES:
    w('/// Every %s route, the one the target names LAST.' % tag)
    w('fn all_%s() -> List<Route> {' % tag)
    w('    [' + ',\n     '.join(
        'routed<%s%d>(Method.Get, "%s", (t: Bytes) -> %s%d.parse(t), h_%s%d)'
        % (tag.upper(), i, pat % name(i), tag.upper(), i, tag, i)
        for i in range(N)) + ']')
    w('}')
    w('')
w('fn asked(line: string) -> Request<Unrouted> {')
w('    let raw = (line + "\\r\\nHost: h\\r\\n\\r\\n").bytes()')
w('    match framed(raw, 0, 0, limits()) {')
w('        .Complete(head) -> Request { raw: raw, head: head, body: Body.Empty, peer: "b", params: Unrouted {} },')
w('        .Partial -> asked(line),')
w('        .Refused(_) -> asked(line),')
w('    }')
w('}')
w('/// THE REFERENCE THE TABLE IS MEASURED AGAINST — a scan down the')
w('/// declared list, trying every route of the right method and width.')
w('/// It lives here rather than in the library because the library')
w('/// ships ONE dispatch door, and this is the algorithm that door had')
w('/// to beat. The widths are precomputed, as a hand-written scan would')
w('/// do, so the comparison is against the fast form of the naive way.')
w('fn scan(rows: List<Route>, widths: List<int>, q: Request<Unrouted>) -> Response {')
w('    let target = q.raw.slice(q.head.target.lo, q.head.target.hi)')
w('    let width = segments(target)')
w('    // LICENSED loops.push_loop: a scan stops at its first answer')
w('    for j, r in rows {')
w('        if r.method == q.head.method && widths[j] == width {')
w('            let answer: Response? = r.serve(q, target)')
w('            if answer != null { return answer! }')
w('        }')
w('    }')
w('    status(404)')
w('}')
w('')
w('fn scanned(rows: List<Route>, widths: List<int>, q: Request<Unrouted>, runs: int) -> int {')
w('    mut ok = 0')
w('    // LICENSED loops.push_loop: a timed loop counts, it does not build a list')
w('    for i in 0..runs {')
w('        if scan(rows, widths, q).status == 200 { ok = ok + 1 }')
w('    }')
w('    ok')
w('}')
w('')
w('fn tabled(t: Table, q: Request<Unrouted>, runs: int) -> int {')
w('    mut ok = 0')
w('    // LICENSED loops.push_loop: a timed loop counts, it does not build a list')
w('    for i in 0..runs {')
w('        if dispatch(t, q).status == 200 { ok = ok + 1 }')
w('    }')
w('    ok')
w('}')
w('')
w('/// Nanoseconds per scan, or -1 when a run did not answer 200 — so a')
w('/// table that never matched cannot read as a fast one.')
w('fn scan_cost(rows: List<Route>, line: string, runs: int) -> int {')
w('    let q = asked(line)')
w('    let widths = [segments(r.pattern.bytes()) for r in rows]')
w('    let start = now_ns()')
w('    let ok = scanned(rows, widths, q, runs)')
w('    let spent = now_ns() - start')
w('    if ok != runs { return 0 - 1 }')
w('    spent / runs')
w('}')
w('')
w('/// Nanoseconds per dispatch through the compiled table. The compile')
w('/// is OUTSIDE the clock, which is the whole point of a `once fn`.')
w('fn table_cost(rows: List<Route>, line: string, runs: int) -> int {')
w('    let q = asked(line)')
w('    let t = compiled(rows)')
w('    let start = now_ns()')
w('    let ok = tabled(t, q, runs)')
w('    let spent = now_ns() - start')
w('    if ok != runs { return 0 - 1 }')
w('    spent / runs')
w('}')
w('')
w('/// What compiling the table costs, once, in nanoseconds.')
w('fn compile_cost(rows: List<Route>) -> int {')
w('    let start = now_ns()')
w('    let t = compiled(rows)')
w('    now_ns() - start - 0 * t.nodes.length')
w('}')
w('')
w('let runs = 50000')
w('let flat = all_flat()')
w('let deep = all_deep()')
w('let wild = all_wild()')
for n in SIZES:
    w('let scan%d = scan_cost(flat.slice(%d, %d), "GET %s HTTP/1.1", runs)'
      % (n, N - n, N, SHAPES[0][2] % name(N - 1)))
    w('let tab%d = table_cost(flat.slice(%d, %d), "GET %s HTTP/1.1", runs)'
      % (n, N - n, N, SHAPES[0][2] % name(N - 1)))
for tag, _, hit in SHAPES[1:]:
    w('let scan_%s = scan_cost(%s, "GET %s HTTP/1.1", runs)' % (tag, tag, hit % name(N - 1)))
    w('let tab_%s = table_cost(%s, "GET %s HTTP/1.1", runs)' % (tag, tag, hit % name(N - 1)))
w('let build300 = compile_cost(flat)')
w('"runs ${runs} | ' +
  ' | '.join('flat %d: scan ${scan%d} table ${tab%d}' % (n, n, n) for n in SIZES) +
  ' | ' + ' | '.join('%s 300: scan ${scan_%s} table ${tab_%s}' % (t, t, t) for t, _, _ in SHAPES[1:]) +
  ' | compile 300 ${build300} ns"')

here = os.path.dirname(os.path.abspath(__file__))
tree = os.path.join(here, "..", "..", "..")
main = os.path.join(here, "src", "main.av")
with open(main, "w") as f:
    f.write("\n".join(out) + "\n")
subprocess.run([os.path.join(tree, "build", "avra"), "fmt", "--write", main], check=True, stdout=subprocess.DEVNULL)
