/* GENERATED by `avra runtime-header` from `rt_sigs()`
   (packages/std-avrac/src/core/runtime_api.av). DO NOT EDIT —
   regenerate it; `make rt-header` refuses a header the rows did not
   make.

   THE ROWS ARE THE DEFINITION AND THIS IS THEIR CLAIM ON THE C.
   Each row asserts, in the C compiler, that the body implementing
   it answers the width the row names and takes the seats the row
   names. Included LAST by runtime/avra_runtime.c, so every body
   above it is already declared.

   WHAT IT HOLDS: the answer's C type, exactly — a body answering
   `int` where the row says i64 writes only the low half and a
   negative value reads back as a large positive one; the seat
   COUNT; and a word handed to a pointer seat, or a pointer handed
   to a word seat.

   WHAT IT DOES NOT HOLD, stated here because a limit belongs where
   the artifact is: an `int64_t` seat against a `double` one. C
   converts between them silently in BOTH directions, so no call
   expression can tell them apart — measured, clang 21, under
   -Wall -Werror. A float travels in its own register file, so the
   confusion is a wrong number rather than a wide one: reached
   through a word seat, avra_float_text renders 1.25 as
   7.949934339416169e-275. The f64 rows are held by the float
   program test, which pins those digits.
   A pointer's POINTEE and its const are not widths and are not read.

   THE PROBES ARE NON-ZERO ON PURPOSE. `((int64_t)0)` is an integer
   constant expression of value zero, which C reads as a NULL
   POINTER CONSTANT: it fills a pointer seat silently, and the
   check that a word cannot would have passed on every row while
   holding nothing. An encoding spends the empty value, so the
   empty case is the first case written (CLAUDE.md). */
#ifndef AVRA_RT_H
#define AVRA_RT_H
#include <stdint.h>

#define AVRA_RT_PTR ((void*)1)
#define AVRA_RT_I64 ((int64_t)1)
#define AVRA_RT_I32 ((int32_t)1)
#define AVRA_RT_U32 ((uint32_t)1)
#define AVRA_RT_F64 ((double)1)

/* A SEAT CANNOT BE VOID. A row that declares one is a defect, and
   it stops at the C compiler with this name unresolved. */
#define AVRA_RT_VOID_SEAT AVRA_RT_a_row_declares_a_void_seat

/* __builtin_classify_type's pointer_type_class. */
#define AVRA_RT_POINTER 5

_Static_assert(__builtin_types_compatible_p(__typeof__(avra_puts(AVRA_RT_PTR)), void),
    "avra_puts: its row answers void, so its C body answers void");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_streq(AVRA_RT_PTR, AVRA_RT_PTR)), int64_t),
    "avra_streq: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_rc_release(AVRA_RT_PTR)), void),
    "avra_rc_release: its row answers void, so its C body answers void");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_rc_retain(AVRA_RT_PTR)), void),
    "avra_rc_retain: its row answers void, so its C body answers void");
_Static_assert(__builtin_classify_type(avra_array_new()) == AVRA_RT_POINTER,
    "avra_array_new: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_array_sized(AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_array_sized: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_array_push(AVRA_RT_PTR, AVRA_RT_I64)), void),
    "avra_array_push: its row answers void, so its C body answers void");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_array_push_owned(AVRA_RT_PTR, AVRA_RT_PTR)), void),
    "avra_array_push_owned: its row answers void, so its C body answers void");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_array_get(AVRA_RT_PTR, AVRA_RT_I64)), int64_t),
    "avra_array_get: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_array_get_owned(AVRA_RT_PTR, AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_array_get_owned: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_cell_release(AVRA_RT_PTR)), void),
    "avra_cell_release: its row answers void, so its C body answers void");
_Static_assert(__builtin_classify_type(avra_cell_unique(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_cell_unique: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_map_new()) == AVRA_RT_POINTER,
    "avra_map_new: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_map_len(AVRA_RT_PTR)), int64_t),
    "avra_map_len: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_map_has(AVRA_RT_PTR, AVRA_RT_PTR)), int64_t),
    "avra_map_has: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_map_get(AVRA_RT_PTR, AVRA_RT_PTR)), int64_t),
    "avra_map_get: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_map_get_owned(AVRA_RT_PTR, AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_map_get_owned: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_map_set(AVRA_RT_PTR, AVRA_RT_PTR, AVRA_RT_I64)), void),
    "avra_map_set: its row answers void, so its C body answers void");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_map_set_owned(AVRA_RT_PTR, AVRA_RT_PTR, AVRA_RT_PTR)), void),
    "avra_map_set_owned: its row answers void, so its C body answers void");
_Static_assert(__builtin_classify_type(avra_slot_unique(AVRA_RT_PTR, AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_slot_unique: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_slot_set(AVRA_RT_PTR, AVRA_RT_I64, AVRA_RT_I64)), void),
    "avra_slot_set: its row answers void, so its C body answers void");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_slot_set_owned(AVRA_RT_PTR, AVRA_RT_I64, AVRA_RT_PTR)), void),
    "avra_slot_set_owned: its row answers void, so its C body answers void");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_array_len(AVRA_RT_PTR)), int64_t),
    "avra_array_len: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_once_get(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_once_get: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_once_set(AVRA_RT_PTR, AVRA_RT_PTR)), void),
    "avra_once_set: its row answers void, so its C body answers void");
_Static_assert(__builtin_classify_type(avra_str_join(AVRA_RT_PTR, AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_str_join: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_insist(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_insist: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_insist_scalar(AVRA_RT_I64, AVRA_RT_I64)), int64_t),
    "avra_insist_scalar: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_str_crossing(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_str_crossing: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_int_div(AVRA_RT_I64, AVRA_RT_I64)), int64_t),
    "avra_int_div: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_int_mod(AVRA_RT_I64, AVRA_RT_I64)), int64_t),
    "avra_int_mod: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_float_text(AVRA_RT_F64)) == AVRA_RT_POINTER,
    "avra_float_text: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_float_text_bits(AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_float_text_bits: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_int_and(AVRA_RT_I64, AVRA_RT_I64)), int64_t),
    "avra_int_and: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_int_or(AVRA_RT_I64, AVRA_RT_I64)), int64_t),
    "avra_int_or: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_int_xor(AVRA_RT_I64, AVRA_RT_I64)), int64_t),
    "avra_int_xor: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_int_not(AVRA_RT_I64)), int64_t),
    "avra_int_not: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_int_shl(AVRA_RT_I64, AVRA_RT_I64)), int64_t),
    "avra_int_shl: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_int_shr(AVRA_RT_I64, AVRA_RT_I64)), int64_t),
    "avra_int_shr: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_int_text(AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_int_text: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_bool_text(AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_bool_text: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_ints_text(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_ints_text: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_bools_text(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_bools_text: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_strs_text(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_strs_text: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_str_len(AVRA_RT_PTR)), int64_t),
    "avra_str_len: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_array_pop(AVRA_RT_PTR)), int64_t),
    "avra_array_pop: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_array_pop_owned(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_array_pop_owned: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_array_concat(AVRA_RT_PTR, AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_array_concat: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_array_slice(AVRA_RT_PTR, AVRA_RT_I64, AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_array_slice: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_str_contains(AVRA_RT_PTR, AVRA_RT_PTR)), int64_t),
    "avra_str_contains: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_str_starts_with(AVRA_RT_PTR, AVRA_RT_PTR)), int64_t),
    "avra_str_starts_with: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_str_ends_with(AVRA_RT_PTR, AVRA_RT_PTR)), int64_t),
    "avra_str_ends_with: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_str_index_of(AVRA_RT_PTR, AVRA_RT_PTR)), int64_t),
    "avra_str_index_of: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_str_substring(AVRA_RT_PTR, AVRA_RT_I64, AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_str_substring: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_str_split(AVRA_RT_PTR, AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_str_split: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_str_replace(AVRA_RT_PTR, AVRA_RT_PTR, AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_str_replace: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_str_char_code(AVRA_RT_PTR, AVRA_RT_I64)), int64_t),
    "avra_str_char_code: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_str_word_at(AVRA_RT_PTR, AVRA_RT_I64)), int64_t),
    "avra_str_word_at: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_str_trim(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_str_trim: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_str_parses_int(AVRA_RT_PTR)), int64_t),
    "avra_str_parses_int: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_str_parsed_int(AVRA_RT_PTR)), int64_t),
    "avra_str_parsed_int: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_bytes_len(AVRA_RT_PTR)), int64_t),
    "avra_bytes_len: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_bytes_eq(AVRA_RT_PTR, AVRA_RT_PTR)), int64_t),
    "avra_bytes_eq: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_bytes_at(AVRA_RT_PTR, AVRA_RT_I64)), int64_t),
    "avra_bytes_at: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_bytes_slice(AVRA_RT_PTR, AVRA_RT_I64, AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_bytes_slice: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_bytes_concat(AVRA_RT_PTR, AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_bytes_concat: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_bytes_index_of(AVRA_RT_PTR, AVRA_RT_PTR, AVRA_RT_I64)), int64_t),
    "avra_bytes_index_of: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_bytes_of_str(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_bytes_of_str: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_bytes_of_list(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_bytes_of_list: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_str_of_bytes(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_str_of_bytes: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_utf8_bad_at(AVRA_RT_PTR)), int64_t),
    "avra_utf8_bad_at: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_bytes_run(AVRA_RT_PTR, AVRA_RT_I64, AVRA_RT_PTR)), int64_t),
    "avra_bytes_run: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_bytes_eq_at(AVRA_RT_PTR, AVRA_RT_I64, AVRA_RT_I64, AVRA_RT_PTR)), int64_t),
    "avra_bytes_eq_at: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_bytes_ieq_at(AVRA_RT_PTR, AVRA_RT_I64, AVRA_RT_I64, AVRA_RT_PTR)), int64_t),
    "avra_bytes_ieq_at: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_bytes_gathered(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_bytes_gathered: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_bytes_adopted(AVRA_RT_PTR, AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_bytes_adopted: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_fd_read(AVRA_RT_I64, AVRA_RT_I64)), int64_t),
    "avra_fd_read: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_fd_taken(AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_fd_taken: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_fd_write(AVRA_RT_I64, AVRA_RT_PTR, AVRA_RT_I64)), int64_t),
    "avra_fd_write: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_str_concat(AVRA_RT_PTR, AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_str_concat: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_errno_text(AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_errno_text: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_now_ns()), int64_t),
    "avra_now_ns: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_host_env(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_host_env: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_selfhost_read_file(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_selfhost_read_file: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_eputs(AVRA_RT_PTR)), void),
    "avra_eputs: its row answers void, so its C body answers void");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_io_list(AVRA_RT_PTR)), int64_t),
    "avra_io_list: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_classify_type(avra_str_from_codepoint(AVRA_RT_I64)) == AVRA_RT_POINTER,
    "avra_str_from_codepoint: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_classify_type(avra_embed(AVRA_RT_PTR)) == AVRA_RT_POINTER,
    "avra_embed: its row answers ptr, so its C body answers a pointer");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_exec_self(AVRA_RT_PTR)), int64_t),
    "avra_exec_self: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_spawn_status(AVRA_RT_PTR, AVRA_RT_PTR)), int64_t),
    "avra_spawn_status: its row answers i64, so its C body answers int64_t");
_Static_assert(__builtin_types_compatible_p(__typeof__(avra_spawn_in(AVRA_RT_PTR, AVRA_RT_PTR, AVRA_RT_PTR)), int64_t),
    "avra_spawn_in: its row answers i64, so its C body answers int64_t");

#endif
