// GENERATED by realize/dom/wire.av (`host_table`) — never edited. `make ui-host` checks it.
export const WIRE_VERSION = 9;
export const NO_ID = -1;
export const OP = { create: 1, create_text: 2, place: 3, remove: 4, set_attr: 5, drop_attr: 6, set_prop: 7, set_text: 8, listen: 9, unlisten: 10, style: 11 };
export const SAYS = { nothing: 0, number: 1, flag: 2, text: 3 };
export const HOST = { entry: "avra_main", event: "@std.ui.web.host_event", seat: "@std.ui.web.host_seat" };
