[package]
name = "validate-bench-rust"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
garde = { version = "0.22", features = ["derive", "email"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[workspace]
