[package]
name        = "cli"
version     = "0.0.1"
description = "The avra command"

[dependencies]
"@std/avrac" = { path = "../std-avrac" }
"@std/cli"   = { path = "../std-cli" }
"@std/toml"  = { path = "../std-toml" }
"@std/testing" = { path = "../std-testing" }
