[package]
name        = "@std/derive"
version     = "0.0.1"
description = "Derivable traits — `@derive(Show)`, `@derive(Eq)`"

[lib]
name = "std-derive"
path = "src/derive.av"

[dependencies]
"@std/meta" = { path = "../std-meta" }
