[package]
name        = "@std/avrac"
version     = "0.0.1"
description = "Avra compiler library"

[lib]
name = "std-avrac"
path = "src/avrac.av"

[dependencies]
"@std/errors" = { path = "../std-errors" }
"@std/toml"   = { path = "../std-toml" }
